# Copyright 2016 Hewlett-Packard Development Company, L.P.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do
# so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# END OF TERMS AND CONDITIONS

# Tested with docker-compose version 1.7.0
version: '2'
services:
  he:
    image: chatopshpe/hubot-enterprise:v0.4.1
    env_file: 
      - .env
      - .env_proxy
    environment:
      HE_ENABLE_AUTH: 1
      HE_AUTH_SERVICE_ENDPOINT: https://auth:3000
      HUBOT_LOG_LEVEL: debug
      ADAPTER: slack
      SLACK_APP_TOKEN:
      HUBOT_SLACK_TOKEN:
    networks:
      - auth_net
    volumes:
      - $HE_INTEGRATION_LOCAL_PATH:/integration
  identity-portal:
    image: he-portal-with-fixes
    env_file: 
      - .env_proxy    
    networks:
      - proxy_net
      - idp_net
      - auth_net
    environment:
      HE_REDIS_HOST: transient-datastore
      HE_REDIS_PORT: 6379
      HE_AUDIENCE: "<your-products-audience>"
      HE_ISSUER: "<this-would-be-you>"
      FLUENTD_HOST:
      FLUENTD_PORT:
    depends_on:
      - transient-datastore
    volumes:
      - $PWD/certs:/server/certs
  proxy:
    image: nginx:1.11-alpine
    volumes:
      - $PWD/certs:/etc/nginx/external
      - $PWD/nginx.conf:/etc/nginx/conf.d/docker-registry.conf
    ports:
      - "443:443"
    networks:
      - proxy_net
    depends_on:
      - identity-portal
  transient-datastore:
    image: redis:3.2-alpine
    networks:
      - idp_net
  auth:
    # TODO: change to a versioned image
    image: chatopshpe/he-auth-service:v0.1.5
    env_file: 
      - .env_proxy  
    environment:
      HE_AUTH_MOCK_AUTH: "true"
      HE_ISSUER: "<this-would-be-you>"
      HE_AUDIENCE: "<your-products-audience>"
      # TODO: make this not required
      HE_AUTH_SSL_PASS: ""
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      HE_VAULT_HOST: vault
      HE_VAULT_PORT: 8200
      HE_IDENTITY_PORTAL_ENDPOINT: https://localhost
      HE_IDENTITY_WS_ENDPOINT: ws://identity-portal:3001
    depends_on:
      - vault
      - identity-portal
    volumes:
      - ./certs:/usr/src/app/certs
    networks:
      - auth_net
      - vault_net
  vault:
    image: vault:0.6.1
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      # need to bind to 0.0.0.0 so that it accepts remote connections (!localhost)
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    networks:
      - vault_net
# TODO: limit visibility of docker containers if possible.
networks:
  proxy_net:
  idp_net:
  auth_net:
  vault_net: